version: '3.9'
services:
  frontend:
    image: northgateweb-frontend:latest
    volumes:
      - .:/app
      - '/app/node_modules'
    ports:
      - "3001:3000"
    networks:
      - web
networks:
  web:
    driver: overlay